"""
YouTube 쿠키 파일 생성 및 관리 함수
"""

from pkg_py.functions_split.ensure_printed import ensure_printed
from pkg_py.system_object.files import F_YOUTUBE_COOKIES_TXT
import os
import subprocess

def ensure_youtube_cookies_created():
    """
    YouTube 쿠키 파일을 생성하는 함수
    
    Returns:
        bool: 쿠키 파일 생성 성공 여부
    """
    try:
        # 쿠키 파일이 이미 존재하는지 확인
        if os.path.exists(F_YOUTUBE_COOKIES_TXT):
            ensure_printed(f"✅ YouTube 쿠키 파일이 이미 존재합니다: {F_YOUTUBE_COOKIES_TXT}", print_color="green")
            return True
        
        # 쿠키 파일 생성 안내
        ensure_printed("🍪 YouTube 쿠키 파일을 생성해야 합니다.", print_color="yellow")
        ensure_printed("📝 다음 단계를 따라하세요:", print_color="cyan")
        ensure_printed("1. 브라우저에서 YouTube에 로그인", print_color="cyan")
        ensure_printed("2. 개발자 도구 열기 (F12)", print_color="cyan")
        ensure_printed("3. Application/Storage 탭에서 Cookies 확인", print_color="cyan")
        ensure_printed("4. 쿠키를 Netscape 형식으로 내보내기", print_color="cyan")
        ensure_printed(f"5. 파일을 다음 경로에 저장: {F_YOUTUBE_COOKIES_TXT}", print_color="cyan")
        
        # 쿠키 파일 템플릿 생성
        cookie_template = """# Netscape HTTP Cookie File
# This file is generated by yt-dlp.  Do not edit.

.youtube.com	TRUE	/	TRUE	1735689600	VISITOR_INFO1_LIVE
.youtube.com	TRUE	/	TRUE	1735689600	LOGIN_INFO
.youtube.com	TRUE	/	TRUE	1735689600	SID
.youtube.com	TRUE	/	TRUE	1735689600	HSID
.youtube.com	TRUE	/	TRUE	1735689600	SSID
.youtube.com	TRUE	/	TRUE	1735689600	APISID
.youtube.com	TRUE	/	TRUE	1735689600	SAPISID
.youtube.com	TRUE	/	TRUE	1735689600	__Secure-1PSID
.youtube.com	TRUE	/	TRUE	1735689600	__Secure-3PSID
.youtube.com	TRUE	/	TRUE	1735689600	__Secure-1PAPISID
.youtube.com	TRUE	/	TRUE	1735689600	__Secure-3PAPISID
"""
        
        # 쿠키 파일 생성
        with open(F_YOUTUBE_COOKIES_TXT, 'w', encoding='utf-8') as f:
            f.write(cookie_template)
        
        ensure_printed(f"📄 쿠키 파일 템플릿이 생성되었습니다: {F_YOUTUBE_COOKIES_TXT}", print_color="green")
        ensure_printed("⚠️ 실제 쿠키 값으로 교체해야 합니다.", print_color="yellow")
        
        return True
        
    except Exception as e:
        ensure_printed(f"❌ 쿠키 파일 생성 실패: {e}", print_color="red")
        return False

def get_youtube_cookies_help():
    """
    YouTube 쿠키 생성 도움말을 출력하는 함수
    """
    help_text = """
🍪 YouTube 쿠키 생성 방법:

1. 브라우저에서 YouTube에 로그인
2. 개발자 도구 열기 (F12)
3. Application/Storage 탭에서 Cookies 확인
4. 쿠키를 Netscape 형식으로 내보내기
5. 파일을 다음 경로에 저장: {cookie_file}

💡 쿠키 브라우저 확장 프로그램 사용:
- Chrome: "Get cookies.txt" 확장 프로그램
- Firefox: "cookies.txt" 확장 프로그램

🔗 유용한 링크:
- https://github.com/yt-dlp/yt-dlp/wiki/FAQ#how-do-i-pass-cookies-to-yt-dlp
- https://github.com/yt-dlp/yt-dlp/wiki/Extractors#exporting-youtube-cookies
""".format(cookie_file=F_YOUTUBE_COOKIES_TXT)
    
    ensure_printed(help_text, print_color="cyan")

if __name__ == "__main__":
    ensure_youtube_cookies_created()
    get_youtube_cookies_help() 