import os
from pkg_py.functions_split.ensure_printed import ensure_printed


def save_chrome_youtube_cookies_to_f():
    """
    Chrome 브라우저에서 YouTube 쿠키를 추출하여 파일로 저장하는 함수
    
    Returns:
        bool: 쿠키 저장 성공 여부
    """
    import browser_cookie3
    from pkg_py.system_object.files import F_YOUTUBE_COOKIES_TXT

    try:
        # Chrome에서 YouTube 쿠키 가져오기
        cj = browser_cookie3.chrome(domain_name=".youtube.com")
        
        # 쿠키 파일 생성
        with open(file=F_YOUTUBE_COOKIES_TXT, mode="w", encoding='utf-8') as f:
            # Netscape 형식 헤더 추가
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# This file is generated by yt-dlp. Do not edit.\n\n")
            
                    # 쿠키 데이터 작성
        for cookie in cj:
            # 만료 시간이 None이면 0으로 설정
            expires = cookie.expires if cookie.expires else 0
            # secure 플래그 설정 (HTTPS 쿠키인 경우)
            secure = "TRUE" if cookie.secure else "FALSE"
            f.write(f"{cookie.domain}\tTRUE\t{cookie.path}\t{secure}\t{expires}\t{cookie.name}\t{cookie.value}\n")
        
        ensure_printed(f" YouTube 쿠키가 성공적으로 저장되었습니다: {F_YOUTUBE_COOKIES_TXT}", print_color="green")
        ensure_printed(f" 저장된 쿠키 개수: {len(list(cj))}", print_color="cyan")
        return True
        
    except ImportError:
        ensure_printed(" browser_cookie3 라이브러리가 설치되지 않았습니다.", print_color="red")
        ensure_printed(" 설치 방법: pip install browser-cookie3", print_color="yellow")
        ensure_printed(" 또는: uv add browser-cookie3", print_color="yellow")
        return False
    except Exception as e:
        ensure_printed(f" 쿠키 저장 실패: {e}", print_color="red")
        return False
